# Physics constants
GRAVITY = 9.81
GAS_CONSTANT = 8.314
DEFAULT_TEMPERATURE = 300.0

# Material types
MATERIAL_TYPE_VACUUM = 0
MATERIAL_TYPE_UNCOMPRESSED = 1
MATERIAL_TYPE_COMPRESSED = 2

# Particle types
PARTICLE_TYPE_PROTON = 0
PARTICLE_TYPE_ELECTRON = 1
PARTICLE_TYPE_NEUTRON = 2

# Simulation parameters
DEFAULT_TIMESTEP = 0.01
DEFAULT_DAMPING = 0.99
DEFAULT_VISCOSITY = 0.01

# Grid parameters
DEFAULT_GRID_SIZE = 10.0
DEFAULT_RESOLUTION = 32
DEFAULT_MAX_DEPTH = 2

# Performance settings
BATCH_SIZE = 1000
INFLUENCE_RADIUS = 3